version: '3.4'

networks:
  camunda-net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.41.0
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - camunda-net
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.2.8
    networks:
      - camunda-net
    ports:
      - 3000:3000



volumes:
  prometheus_data:
  grafana_data: