version: "3.7"

services:
  
  #KeyCloak(SSO)
  #link: localhost:8085
  keycloak-authorization-server:
    container_name: keycloak-authorization-server
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER} 
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
    ports:
      - 8085:8080
    command:
      - start-dev
    networks:
      - stack1-network
  
  
  #DataBase 1
  postgres_calendario:
    container_name: postgres_calendario_service
    image: postgres:12.2
    environment:
      DATABASE_HOST: localhost
      POSTGRES_DB: calendario_service
      POSTGRES_USER: calendario
      POSTGRES_PASSWORD: calendario
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped      
    networks:
      - stack1-network
    

networks:
  stack1-network:
    driver: bridge  
    
    
 